version: '3.8'
services:
  nextjs:
    container_name: 'next-app'
    build:
      context: .
      dockerfile: Dockerfile
    image: 'next-app'
    ports:
      - '3000:3000'
  nginx:
    image: nginx:latest
    ports:
      - '4204:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs
