services:
  angular-app:
    container_name: angular-app
    build:
      context: ./angular-app

  react-app:
    container_name: react-app
    build:
      context: ./react-app

  vue-app:
    container_name: vue-app
    build:
      context: ./vue-app

  orchestrator:
    container_name: orchestrator
    image: 'orchestrator'
    ports:
      - '8081:80'
    depends_on:
      - angular-app
      - react-app
      - vue-app
    build:
      context: .
      dockerfile: Dockerfile
